- id: '1572347519678'
  alias: Pooltemp under 10
  description: Dags att stänga poolen
  trigger:
  - above: '-10'
    below: '10'
    entity_id: sensor.ow_pool_temp_rounded
    for: '24:00:00'
    platform: numeric_state
  condition:
  - condition: template
    value_template: '{{ as_timestamp(now()) - as_timestamp(states.automation.pooltemp_under_10.attributes.last_triggered)
      | int > 16000000}}'
  action:
  - data:
      message: Dags att stänga ner poolen för vintern, temperaturen är just nu {{
        states('sensor.ow_pool_temp_rounded') }} grader.
    service: notify.slack_notify
- id: '1576416157907'
  alias: Monitor ESP Home devices - offline
  description: Notification when they go offline
  trigger:
  - entity_id: binary_sensor.engine_heater_status, binary_sensor.pannrum, binary_sensor.pool_house_status,
      binary_sensor.poolhus, binary_sensor.pannrumsstyrning
    for: 00:10:00
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data_template:
      message: En ESP Home enhet {{ trigger.from_state.attributes.friendly_name }}
        har varit offline i mer än 5 minuter nu.
    service: notify.slack_notify
- id: '1576416157709'
  alias: Monitor ESP Home devices - online
  description: Notification when they go online
  trigger:
  - entity_id: binary_sensor.engine_heater_status, binary_sensor.pannrum, binary_sensor.pool_house_status,
      binary_sensor.poolhus, binary_sensor.pannrumsstyrning
    for: 00:02:00
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: template
    value_template: '{{ as_timestamp(now()) - as_timestamp(states.automation.monitor_esp_home_devices_offline.attributes.last_triggered)
      | int < 300}}'
  action:
  - data_template:
      message: En ESP Home enhet {{ trigger.from_state.attributes.friendly_name }}
        gick online.
    service: notify.slack_notify
