- id: '1545336829164'
  alias: Slack test
  trigger:
  - at: '14:00:00'
    platform: time
  condition: []
  action:
  - data:
      message: Slack test again
    service: notify.slack_notify
- id: '1570009071055'
  alias: Teknikshakt tempvarning
  trigger:
  - above: '-10'
    below: '5'
    entity_id: sensor.ow_pool_techroom_temp_rounded
    for:
      hours: 2
    platform: numeric_state
  condition: []
  action:
  - data:
      message: Det är kallt i teknikshaktet, {{ states('sensor.ow_pool_techroom_temp_rounded')
        }} grader.
    service: notify.slack_notify
- id: '1572347519678'
  alias: Pooltemp under 10
  description: Dags att stänga poolen
  trigger:
  - above: '-10'
    below: '10'
    entity_id: sensor.ow_pool_temp_rounded
    for: '24:00:00'
    platform: numeric_state
  condition: []
  action:
  - data:
      message: Dags att stänga ner poolen för vintern, temperaturen är just nu {{
        states('sensor.ow_pool_temp_rounded') }} grader.
    service: notify.slack_notify
- id: '1572377204755'
  alias: Test time triggering
  description: Trigger based on time and last execution
  trigger:
  - at: 08:05:00
    platform: time
  condition:
  - condition: template
    value_template: '{{ as_timestamp(now()) - as_timestamp(states.automation.test_time_triggering.attributes.last_triggered)
      | int > 200}}'
  action:
  - data:
      message: testing
    service: notify.slack_notify
- id: '1576416157907'
  alias: Monitor ESP Home devces
  description: ''
  trigger:
  - entity_id: binary_sensor.engine_heater_status
    for: 00:05:00
    from: 'on'
    platform: state
    to: 'off'
  - entity_id: binary_sensor.pannrum
    for: 00:05:00
    from: 'on'
    platform: state
    to: 'off'
  - entity_id: binary_sensor.pool_house_status
    for: 00:05:00
    from: 'on'
    platform: state
    to: 'off'
  - entity_id: binary_sensor.poolhus
    for: 00:05:00
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      message: En ESP Home enhet har varit offline i mer än 5 minuter nu.
    service: notify.slack_notify
- id: '12345'
  alias: Pellet level warning 50%
  trigger:
  - above: '20.0'
    below: '50.0'
    entity_id: sensor.filtered_pellet_level
    for:
      hours: 1
    platform: numeric_state
  condition:
  - condition: template
    value_template: '{{ as_timestamp(now()) - as_timestamp(states.automation.filtered_pellet_level_warning_50.attributes.last_triggered)
      | int > 259200 }}'
  action:
  - data:
      message: Det är cirka 50 procent pellets i tunnan
    service: notify.slack_notify
- id: '23456'
  alias: Pellet level warning 20%
  trigger:
  - above: '0.0'
    below: '20.0'
    entity_id: sensor.filtered_pellet_level
    for:
      hours: 1
    platform: numeric_state
  condition:
  - condition: template
    value_template: '{{ as_timestamp(now()) - as_timestamp(states.automation.filtered_pellet_level_warning_20.attributes.last_triggered)
      | int > 259200 }}'
  action:
  - data:
      message: Det är cirka 20 procent pellets i tunnan
    service: notify.slack_notify
