- id: '1576416157907'
  alias: Monitor ESP Home devices - offline
  description: Notification when they go offline
  trigger:
  - entity_id: binary_sensor.pannrum, binary_sensor.pool_house_status, binary_sensor.poolhus,
      binary_sensor.pannrumsstyrning
    for: 00:10:00
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data_template:
      message: En ESP Home enhet {{ trigger.from_state.attributes.friendly_name }}
        har varit offline i mer än 5 minuter nu.
    service: notify.slack_notify
  mode: single
- id: '1576416157709'
  alias: Monitor ESP Home devices - online
  description: Notification when they go online
  trigger:
  - entity_id: binary_sensor.engine_heater_status, binary_sensor.pannrum, binary_sensor.pool_house_status,
      binary_sensor.poolhus, binary_sensor.pannrumsstyrning
    for: 00:02:00
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: template
    value_template: '{{ as_timestamp(now()) - as_timestamp(states.automation.monitor_esp_home_devices_offline.attributes.last_triggered)
      | int < 300}}'
  action:
  - data_template:
      message: En ESP Home enhet {{ trigger.from_state.attributes.friendly_name }}
        gick online.
    service: notify.slack_notify
- id: '1639476450382'
  alias: deCONZ - Tradfri Shortcut Button
  description: ''
  use_blueprint:
    path: Sam04/deconz-ikea-tradfri-shortcut-button.yaml
    input:
      remote: 1633905cadfba2fcd62f67f75f0bd40b
      button_short:
      - type: toggle
        device_id: b3621241cf76fa5c4effec9c92d02264
        entity_id: light.shelly1_fonsterlampor_vardagsrum
        domain: light
