- id: '1576416157907'
  alias: Monitor ESP Home devices - offline
  description: Notification when they go offline
  trigger:
  - entity_id: binary_sensor.pannrum, binary_sensor.pool_house_status, binary_sensor.poolhus,
      binary_sensor.pannrumsstyrning
    for: 00:10:00
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data_template:
      message: En ESP Home enhet {{ trigger.from_state.attributes.friendly_name }}
        har varit offline i mer än 5 minuter nu.
    service: notify.slack_notify
  mode: single
- id: '1576416157709'
  alias: Monitor ESP Home devices - online
  description: Notification when they go online
  trigger:
  - entity_id: binary_sensor.engine_heater_status, binary_sensor.pannrum, binary_sensor.pool_house_status,
      binary_sensor.poolhus, binary_sensor.pannrumsstyrning
    for: 00:02:00
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: template
    value_template: '{{ as_timestamp(now()) - as_timestamp(states.automation.monitor_esp_home_devices_offline.attributes.last_triggered)
      | int < 300}}'
  action:
  - data_template:
      message: En ESP Home enhet {{ trigger.from_state.attributes.friendly_name }}
        gick online.
    service: notify.slack_notify
- id: '1639476450382'
  alias: SB1 Trådfri button
  description: ''
  use_blueprint:
    path: Sam04/deconz-ikea-tradfri-shortcut-button.yaml
    input:
      remote: 1633905cadfba2fcd62f67f75f0bd40b
      button_short:
      - service: input_button.press
        data: {}
        target:
          entity_id: input_button.sb1_short_press
- id: '1644057288305'
  alias: Värmepanna Fyllning Pelletssäckar
  description: ''
  trigger:
  - platform: state
    entity_id: input_button.confirmpelletfill
  condition: []
  action:
  - service: notify.slack_notify
    data:
      title: Fyllning av pelllets
      target: homeautomation_logs
      message: Automation fyllning av pellets påbörjad
  - service: counter.configure
    data_template:
      entity_id: counter.pelletssackar
      value: ' {{ states(''counter.pelletssackar'')|int + states(''input_number.pelletssackar_fyllning'')|int
        }}'
  - service: counter.configure
    data_template:
      entity_id: counter.pelletssackar_lager
      value: ' {{ states(''counter.pelletssackar_lager'')|int - states(''input_number.pelletssackar_fyllning'')|int
        }}'
  - service: button.press
    data: {}
    target:
      entity_id: button.esp_pannrum_restart
  - delay:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  - service: daily_min_max.reset
    data: {}
    target:
      entity_id: sensor.pellets_kg_daily_min
  - service: utility_meter.calibrate
    data:
      value: '0'
    target:
      entity_id: sensor.pellets_kg_since_last_fill
  - service: notify.larre_phone
    data:
      message: Pellets har fyllts.
      title: Pellets
  - service: notify.slack_notify
    data:
      title: Fyllning av pelllets
      target: homeautomation_logs
      message: '{{ states.person|selectattr("attributes.user_id", "==", trigger.to_state.context.user_id)|map(attribute="attributes.friendly_name")|first
        }} fyllde {{ states(''input_number.pelletssackar_fyllning'') }} säckar pellets'
  mode: single
- id: '1644133469590'
  alias: Värmepanna återställ årlig förbrukning
  description: ''
  trigger:
  - platform: time
    at: 01:00:00
  condition:
  - condition: template
    value_template: '{{ now().day == 1 }}'
  - condition: template
    value_template: '{{ now().month == 7 }}'
  action:
  - service: input_number.set_value
    data_template:
      entity_id: input_number.pelletssackar_forbrukning_foregaende_ar
      value: '{{ states(''counter.pelletssackar'')|int }}'
  - device_id: 8c9f21ef026511eb8d9c83356b64f543
    domain: mobile_app
    type: notify
    message: Återställde årlig förbrukning pellets
    title: Återställning
  - service: notify.slack_notify
    data:
      title: Återställning
      target: homeautomation
      message: Återställde årlig förbrukning pellets, totalt {{ states('counter.pelletssackar')
        }} säckar
  - service: counter.reset
    data: {}
    target:
      entity_id: counter.pelletssackar
  mode: single
- id: '1646074081872'
  alias: Soptunnor Påminnelse
  description: Skickar påminnelse om att ta ut soptunnorna om inte gjort innan 20.00
  trigger:
  - platform: time
    at: '20:00:00'
  - platform: time
    at: '21:00:00'
  - platform: time
    at: '22:00:00'
  condition:
  - condition: state
    entity_id: input_boolean.satta_ut_soptunnor
    state: 'on'
  action:
  - service: notify.larre_phone
    data:
      message: Dags att ta ut tunnorna
      title: Soptunnor
  - service: notify.camilla_phone
    data:
      message: Dags att ta ut tunnorna
      title: Soptunnor
  mode: single
- id: '1646077072609'
  alias: Soptunnor sätt ut Aktivera
  description: ''
  trigger:
  - platform: time
    at: '15:00:00'
  condition:
  - condition: time
    weekday:
    - mon
  - condition: template
    value_template: '{{(as_timestamp(now())|timestamp_custom (''%U'') | int % 2) ==
      1 }}'
  action:
  - service: input_boolean.turn_on
    data: {}
    target:
      entity_id: input_boolean.satta_ut_soptunnor
  mode: single
- id: '1646295058306'
  alias: 'Soptunnor ta in Aktivera '
  description: ''
  trigger:
  - platform: time
    at: 08:00:00
  condition:
  - condition: time
    weekday:
    - tue
  - condition: template
    value_template: '{{(as_timestamp(now())|timestamp_custom (''%U'') | int % 2) ==
      1 }}'
  action:
  - service: input_boolean.turn_on
    data: {}
    target:
      entity_id: input_boolean.ta_in_soptunnor
  mode: single
- id: '1648330926755'
  alias: Cast HA to Kitchen
  description: ''
  use_blueprint:
    path: kind3r/cast-and-re-cast-a-lovelace-view-to-a-google-hub.yaml
    input:
      player: media_player.nest_kok
      view: kok
- id: '1657399504458'
  alias: Trigger notification on Doods detection
  description: ''
  trigger:
  - platform: state
    entity_id:
    - image_processing.doods_poolcam_sd
    attribute: total_matches
  condition:
  - condition: numeric_state
    entity_id: image_processing.doods_poolcam_sd
    attribute: total_matches
    above: '0'
  action:
  - service: notify.slack_notify
    data:
      message: Poolen - objekt upptäckt
      data:
        file:
          path: /config/www/doods_latest.jpg
  - delay:
      hours: 0
      minutes: 10
      seconds: 0
      milliseconds: 0
  mode: single
- id: '1658738419847'
  alias: Snapshot pool camera
  description: ''
  trigger:
  - platform: time_pattern
    minutes: '00'
  condition: []
  action:
  - service: camera.snapshot
    data:
      filename: config/www/snapshots/pool_{{ now().strftime('%Y%m%d%H%M') }}.jpg
    target:
      device_id: 5b8763815cd77fddbef208fd2a3696fd
  - service: shell_command.upload_nyckel_training_image
    data: {}
  - service: system_log.write
    data:
      level: info
      message: '"Took a pool snapshot"'
      logger: Snapshot automation
  mode: single
- id: '1658996877167'
  alias: Tvättmaskin färdig
  description: ''
  trigger:
  - type: power
    platform: device
    device_id: 1ce148b34e70101bb78af834f1efa9af
    entity_id: sensor.tvattmaskin_power
    domain: sensor
    above: 500
    for:
      hours: 0
      minutes: 2
      seconds: 0
  condition: []
  action:
  - wait_for_trigger:
    - type: power
      platform: device
      device_id: 1ce148b34e70101bb78af834f1efa9af
      entity_id: sensor.tvattmaskin_power
      domain: sensor
      below: 10
      for:
        hours: 0
        minutes: 1
        seconds: 0
    continue_on_timeout: false
  - service: notify.larre_phone
    data:
      message: Tvättmaskinen är färdig!
      title: Tvättmaskin
  - service: notify.slack_notify
    data:
      message: Tvättmaskin färdig
      target: homeautomation_logs
  mode: single
- id: '1663259647190'
  alias: SB2 Trådfri button
  description: ''
  use_blueprint:
    path: Sam04/deconz-ikea-tradfri-shortcut-button.yaml
    input:
      remote: 8fc32af68446cb32cd9145d7db711f0a
      button_short:
      - service: input_button.press
        data: {}
        target:
          entity_id: input_button.sb2_short_press
      button_long:
      - service: input_button.press
        data: {}
        target:
          entity_id: input_button.sb2_long_press
- id: '1664945566552'
  alias: Torktumlare färdig
  description: ''
  trigger:
  - type: power
    platform: device
    device_id: f40414b91ad5c50edf9082184d94de06
    entity_id: sensor.torktumlare_power
    domain: sensor
    above: 1000
    for:
      hours: 0
      minutes: 2
      seconds: 0
  condition: []
  action:
  - wait_for_trigger:
    - type: power
      platform: device
      device_id: f40414b91ad5c50edf9082184d94de06
      entity_id: sensor.torktumlare_power
      domain: sensor
      below: 50
      for:
        hours: 0
        minutes: 1
        seconds: 0
    continue_on_timeout: false
  - service: notify.larre_phone
    data:
      message: Torktumlaren är färdig!
      title: Torktumlare
  - service: notify.slack_notify
    data:
      message: Torktumlare färdig
      target: homeautomation_logs
  mode: single
- id: '1666252779539'
  alias: Slimmelezer offline
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.current_phase_1
    to: unknown
    for:
      hours: 0
      minutes: 1
      seconds: 0
  - platform: state
    entity_id:
    - sensor.current_phase_1
    to: unavailable
    for:
      hours: 0
      minutes: 1
      seconds: 0
  condition: []
  action:
  - service: notify.larre_slack
    data:
      message: Slimmelezer offline
      title: Slimmelezer offline?
  - service: notify.larre_phone
    data:
      title: Slimmelezer offline?
      message: Slimmelezer offline
  - service: notify.slack_notify
    data:
      message: Slimmelezer offline
      title: Slimmelezer offline?
      target: homeautomation_logs
  mode: single
- id: '1670082620377'
  alias: Charge Amps reset last charge counters when EV2 is disconnected
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.charge_amps_charging_status
    from: Connected
    to: Available
  - platform: state
    entity_id:
    - sensor.charge_amps_charging_status
    from: Charging
    to: Available
  condition: []
  action:
  - service: notify.slack_notify
    data_template:
      message: Charge Amps senaste laddning {{ states('sensor.charge_amps_last_charge_kwh')
        }} kWh till en kostnad av {{ states('sensor.charge_amps_last_charge_cost')
        | round }} kr
      target: homeautomation
  - service: utility_meter.calibrate
    data:
      value: '0'
    target:
      entity_id:
      - sensor.charge_amps_last_charge_kwh
      - sensor.charge_amps_last_charge_cost
  mode: single
