homeassistant:
  packages: !include_dir_named packages
  name: Home
  latitude: 55.693862
  longitude: 13.231983
  elevation: 29
  unit_system: metric
  time_zone: Europe/Stockholm

  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 172.30.32.0/23
        - 192.168.10.0/24

default_config:

recorder:
  db_url: mysql://homeassistant:r1*snuG0F#6hgEb@core-mariadb/homeassistant?charset=utf8

# Slack App
notify:
  - name: slack_notify
    platform: slack
    api_key: !secret slack_api_key
    default_channel: '#homeautomation'
    username: "HassIO"
    
shelly:

zone:
  - name: Home
    latitude: 55.693862
    longitude: 13.231983
    radius: 50
    icon: mdi:home

# Discover some devices automatically
discovery:

# Sensors
sensor:
  # Weather prediction
  - platform: yr
  ### system monitor ###
  - platform: systemmonitor
    resources:
    - type: disk_use_percent
      arg: /
    - type: disk_free
      arg: /
    - type: memory_use_percent
    - type: last_boot
    - type: processor_use
    
# IOS App settings
ios:

device_tracker:
  - platform: luci
    host: 192.168.10.1
    username: root
    password: !secret router_password

shopping_list:

logger:
  default: warn
  
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml


