homeassistant:
  packages: !include_dir_named packages

  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 172.30.32.0/23
        - 192.168.10.0/24

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - 172.17.0.0/16
    - 172.30.0.0/16
    - 192.168.10.0/24

default_config:

recorder:
  db_url: !secret connectionstring_mariadb
  purge_keep_days: 30
  exclude:
    entities:
      - sensor.helper_bussar_fran_gastelyckan_o
      - sensor.helper_buss_till_botulfsplatsen
      - sensor.helper_bussar_fran_botulfsplatsen

swedish_calendar:

# IOS App settings
ios:

shopping_list:

logger:
  default: info

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
