homeassistant:
  packages: !include_dir_named packages
  
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 55.693862
  longitude: 13.231983
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: CET
  # Customization file
  customize: !include customize.yaml

http:

system_health:

zone:
  - name: Home
    latitude: 55.693862
    longitude: 13.231983
    radius: 50
    icon: mdi:home

# Enables the frontend
frontend:
  themes:  !include themes.yaml

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
#map:

# Track the sun
sun:

# Sensors
sensor:
  # Weather prediction
  - platform: yr


# Text to speech
tts:
  - platform: google

# Cloud
#cloud:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml


weblink:
  entities:
    - name: Unifi Controller
      icon: mdi:access-point-network
      url: https://hass.landin.lan:8443

# panel_iframe
  # configurator:
  #   title: Configurator
  #   icon: mdi:wrench
  #   url: http://hass.landin.lan:3218
    
# Slack App
notify:
  - name: slack_notify
    platform: slack
    api_key: !secret slack_api_key
    default_channel: '#homeautomation'
    username: "HassIO"
    
# IOS App settings
ios:

device_tracker:
  - platform: luci
    host: 192.168.10.1
    username: root
    password: !secret router_password

#Person tracking
person:
  - name: Larre
    id: larre
    user_id: d533fc5016334f9ea95e79d94dbbc3d5
    device_trackers:
      - device_tracker.larre
  - name: Camilla
    id: camilla
    device_trackers:
      - device_tracker.camilla
  - name: Hugo
    id: hugo
    device_trackers:
      - device_tracker.hugo
  - name: Tekla
    id: tekla
    device_trackers:
      - device_tracker.tekla

shopping_list: