homeassistant:
  packages: !include_dir_named packages
  name: Home
  latitude: 55.693862
  longitude: 13.231983
  elevation: 29
  unit_system: metric
  time_zone: CET

default_config:

# Slack App
notify:
  - name: slack_notify
    platform: slack
    api_key: !secret slack_api_key
    default_channel: '#homeautomation'
    username: "HassIO"
    

zone:
  - name: Home
    latitude: 55.693862
    longitude: 13.231983
    radius: 50
    icon: mdi:home

# Discover some devices automatically
discovery:

# Sensors
sensor:
  # Weather prediction
  - platform: yr
# IOS App settings
ios:

device_tracker:
  - platform: luci
    host: 192.168.10.1
    username: root
    password: !secret router_password

shopping_list:

logger:
  default: warn
  
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
person: !include person.yaml

