homeassistant:
  packages: !include_dir_named packages

  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 172.30.32.0/23
        - 192.168.10.0/24

default_config:

recorder:
  db_url: !secret connectionstring_mariadb

# Slack App
notify:
  - name: slack_notify
    platform: slack
    api_key: !secret slack_api_key
    default_channel: '#homeautomation'
    username: "Home Assistant"
    icon: ":octopus:"

chargeamps:
  username: !secret email_larre
  password: !secret chargeamps_password
  api_key: !secret chargeamps_api_key

zone:
  - name: Home
    latitude: 55.693862
    longitude: 13.231983
    radius: 50
    icon: mdi:home

# Discover some devices automatically
discovery:


# Sensors
sensor:
  ### system monitor ###
  - platform: systemmonitor
    resources:
    - type: disk_use_percent
      arg: /
    - type: disk_free
      arg: /
    - type: memory_use_percent
    - type: last_boot
    - type: processor_use


  # Swedish calendar
  - platform: swedish_calendar
    
# IOS App settings
ios:

device_tracker:
  - platform: luci
    host: 192.168.10.1
    username: root
    password: !secret router_password
    consider_home: 240

shopping_list:

logger:
  default: warn
  
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml


