esphome:
  name: elcentral-sonoff
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: 'landin iot'
  password: !secret landin_iot_wifi_password
  domain: '.landin.lan'
  fast_connect: true
  
  manual_ip:
    static_ip: 192.168.10.68
    gateway: 192.168.10.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Elcentral Sonoff"
    password: "bXIbNM9a7UkC"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret esp_api_password

ota:
  password: !secret esp_ota_password

binary_sensor:
  - platform: status
    name: "Elcentral Sonoff status"
  
output:
  - platform: gpio
    pin: GPIO12
    id: relay1
light:
  - platform: binary
    name: "Timeruttag Relä"
    id: light1
    output: relay1