esphome:
  name: engine_heater_sonoff
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: 'landin iot'
  password: !secret landin_iot_wifi_password
  domain: '.landin.lan'
  fast_connect: true
  
  manual_ip:
    static_ip: 192.168.10.63
    gateway: 192.168.10.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Engine Heater Sonoff"
    password: "AfKzGFsMB3n1"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
   password: !secret esp_api_password

ota:
  password: !secret esp_ota_password

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "engine heater button"
    on_press:
      if:
        condition:
          switch.is_off: relay1
        then:
        - switch.turn_on: relay1
        - delay: 1h
        - switch.turn_off: relay1
        else:
        - switch.turn_off: relay1
  - platform: status
    name: "engine heater status"

switch:
  - platform: gpio
    name: "engine heater relay"
    pin: GPIO12
    id: relay1