esphome:
  name: garage-door-esp
  on_boot: 
    then:
      - lock.lock: lock_garage

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret esp_api_password
  
ota:
  password: !secret esp_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: '.landin.lan'
  fast_connect: true

  manual_ip:
    static_ip: 192.168.10.62
    gateway: 192.168.10.1
    subnet: 255.255.255.0

output:
  - platform: gpio
    pin: GPIO0
    id: relay
lock:
  - platform: output
    id: lock_garage
    name: "Garagedörr"
    output: relay

binary_sensor:
  - platform: gpio
    id: door_garage
    name: "Garagedörr"
    device_class: door
    pin:
      # Connected to GPIO on the ESP-01S.
      number: GPIO3
      mode: INPUT_PULLUP
      inverted: false
    filters:
      # Small filter, to debounce the magnet.
      - delayed_on: 25ms
      - delayed_off: 25ms
  - platform: status
    name: "Garagedörr ESP status"

status_led:
  pin: 
    number: GPIO2
    inverted: true
