esphome:
  name: lightsensor_esp
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: 'landin iot'
  password: !secret landin_iot_wifi_password
  domain: '.landin.lan'
  fast_connect: true
  
  manual_ip:
    static_ip: 192.168.10.65
    gateway: 192.168.10.1
    subnet: 255.255.255.0

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret esp_api_password

ota:
  password: !secret esp_ota_password

binary_sensor:
  - platform: status
    name: "Lightsensor ESP"

sensor:
  - platform: adc 
    pin: A0
    name: "Dagsljus ofiltrerat"
    id: daylight_unfiltered
    update_interval: 60s
    unit_of_measurement: "lx"
    filters:       
    - lambda: return 100.0 - (x * 100.0);
    
  - platform: template
    name: "Dagsljus"
    id: daylight_filtered
    unit_of_measurement: "lx"
    lambda: return id(daylight_unfiltered).state;
    filters:
    - exponential_moving_average:
        alpha: 0.1
        send_every: 10

switch:
  - platform: gpio
    pin: D1
    id: red_led
    name: "Red LED"