esphome:
  name: pannrum_esp
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: 'landin iot'
  password: !secret landin_iot_wifi_password
  domain: '.landin.lan'
  fast_connect: true
  
  manual_ip:
    static_ip: 192.168.10.60
    gateway: 192.168.10.1
    subnet: 255.255.255.0

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret esp_api_password

ota:
  password: !secret esp_ota_password

dallas:
  - pin: D7

binary_sensor:
  - platform: status
    name: "Pannrum ESP status"

sensor:
  - platform: ultrasonic
    trigger_pin: D5
    echo_pin: D6
    name: "Pellet Level Raw"
    id: pellet_level_raw
    # filters:
    # - lambda: return ((1.0 - x) / 0.85) * 100;
    # - heartbeat: 300s
    # accuracy_decimals: 

  - platform: template
    name: "Pellet Level Calculated"
    id: pellet_level_calculated
    unit_of_measurement: "%"
    lambda: return ((1.0 - id(pellet_level_raw).state) / 0.85) * 100;

  - platform: template
    name: "Pellet Level"
    id: pellet_level_filtered
    unit_of_measurement: "%"
    lambda: return id(pellet_level_calculated).state;
    filters:
    - sliding_window_moving_average:
        window_size: 30
        send_every: 30

  - platform: dallas
    address: 0x0D0008022A1D9710
    name: "Pannrum"
    filters:
    - heartbeat: 5min
    - sliding_window_moving_average:
        window_size: 30
        send_every: 30
    accuracy_decimals: 0