esphome:
  name: pannrumsstyrning_esp
  platform: ESP32
  board: esp32-poe

  #Start automation script
  on_boot:
    priority: -10
    then:
      - script.execute: shunt_automation


ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 0
  power_pin: GPIO12
  domain: '.landin.lan'
  
  manual_ip:
    static_ip: 192.168.10.66
    gateway: 192.168.10.1
    subnet: 255.255.255.0
# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret esp_api_password

ota:
  password: !secret esp_ota_password

dallas:
  - pin: GPIO4

#Globals
globals:
  - id: shunt_time_seconds
    type: int
    initial_value: '3'
  - id: shunt_pause_time_seconds
    type: int
    initial_value: '10'
  - id: heating_tolerance_degrees
    type: int
    initial_value: '3'
  - id: min_heater_temperature_degrees
    type: int
    initial_value: '40'
  - id: min_goal_temperature_offset_degrees
    type: int
    initial_value: '5'

# Sensors
sensor:
  - platform: dallas
    address: 0x310119143EF32B28
    name: Panntemperatur
    id: furnace_temp
    internal: true
  - platform: dallas
    address: 0xDD0119142F965B28
    id: flow_temperature
    internal: true
  - platform: template
    id: setpoint_flow_temperature
    name: "Börvärde framledning"
    lambda: |-
      return (id(heating_curve).state * (-1) * id(outside_temp).state) + id(heating_offset).state;
    update_interval: 1min
    internal: true
    
    # Values from Home Assistant
  - platform: homeassistant
    name: Heating curve
    entity_id: input_number.heating_curve
    id: heating_curve
  - platform: homeassistant
    name: Heating offset
    entity_id: input_number.heating_offset
    id: heating_offset
  - platform: homeassistant
    name: Heating mintemp
    entity_id: input_number.heating_mintemp
  - platform: homeassistant
    name: Outside temperature
    entity_id: sensor.ow_outside_temp
    id: outside_temp

# Binary sensors
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO3
      mode: INPUT_PULLUP
      inverted: True
    name: "burner error"
  - platform: status
    name: "Pannrumsstyrning"
  - platform: homeassistant
    name: Furnace Heating
    entity_id: binary_sensor.furnace_heating_rising
    id: furnace_heating_rising

#Switches
switch:
  - platform: gpio
    name: "relay shunt open"
    pin: GPIO13
    id: relayshuntopen
    internal: true
  - platform: gpio
    name: "relay shunt close"
    pin: GPIO14
    id: relayshuntclose
    internal: true
  - platform: gpio
    name: "relay burner thermostat"
    pin: GPIO15
    id: relayburnerthermostat
    internal: true
  - platform: gpio
    name: "relay circulation pump"
    pin: GPIO16
    id: relaycirculationpump
    internal: true

#Scripts
script:
  id: shunt_automation
  mode: single
  then:
  - while:
      condition:
        lambda: 'return 1;'
      then:
        - logger.log: "Shunt running"
        - delay: 10s
        # - if:
        #     condition:
        #       lambda: 'return ((float)id(furnace_temp).state + (float)id(flow_temperature).state) > 0.0;'
        #     then:
        #       - logger.log: "Test"
        - if: # Shunta upp  50-3 > framledning
            condition:
              lambda: 'return (float)id(setpoint_flow_temperature).state - id(heating_tolerance_degrees) > (float)id(flow_temperature).state;'
            then:
              - logger.log: "Shuntar upp"
        - if:
            condition:
              lambda: 'return (float)id(setpoint_flow_temperature).state + id(heating_tolerance_degrees) < (float)id(flow_temperature).state ;'
            then:
                - logger.log: "Shuntar ned"