esphome:
  name: pannrumsstyrning_esp
  platform: ESP32
  board: esp32-poe

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 0
  power_pin: GPIO12
  domain: '.landin.lan'
  
  manual_ip:
    static_ip: 192.168.10.66
    gateway: 192.168.10.1
    subnet: 255.255.255.0
# Enable logging
logger:

# Enable Home Assistant API
api:
   password: !secret esp_api_password

ota:
  password: !secret esp_ota_password

binary_sensor:
  - platform: status
    name: "Pannrumsstyrning"
