esphome:
  name: pannrumsstyrning_esp
  platform: ESP32
  board: esp32-poe

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 0
  power_pin: GPIO12
  domain: '.landin.lan'
  
  manual_ip:
    static_ip: 192.168.10.66
    gateway: 192.168.10.1
    subnet: 255.255.255.0
# Enable logging
logger:

# Enable Home Assistant API
api:
   password: !secret esp_api_password

ota:
  password: !secret esp_ota_password

dallas:
  - pin: GPIO4

sensor:
  - platform: dallas
    address: 0x310119143EF32B28
    name: Panntemperatur
  - platform: dallas
    address: 0xDD0119142F965B28
    name: Framledningstemperatur

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO3
      mode: INPUT_PULLUP
      inverted: True
    name: "burner error"
  - platform: status
    name: "Pannrumsstyrning"


