substitutions:
  static_ip: 192.168.10.67

esphome:
  name: poolhus-hornlampor-sonoff
  comment: $static_ip

esp8266:
  board: esp01_1m

wifi:
  ssid: 'landin iot'
  password: !secret landin_iot_wifi_password
  domain: '.landin.lan'
  fast_connect: true
  
  manual_ip:
    static_ip: $static_ip
    gateway: 192.168.10.1
    subnet: 255.255.255.0

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "5KIqhkb9fM5PQ3DmA5IipH3pBByaoA22D0G+5K1hhSA="

ota:
  - platform: esphome
    password: !secret esp_ota_password

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Poolhus Hörnlampor Knapp"
    id: poolhus_hornlampor_button
    on_press:
      then:
      - light.toggle: light1

  - platform: status
    name: "Poolhus Hörnlampor Sonoff status"
output:
  - platform: gpio
    pin: GPIO12
    id: relay1
light:
  - platform: binary
    name: "Hörnlampor Poolhus"
    id: light1
    output: relay1