esphome:
  name: poolhus_heater_sonoff
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: 'landin iot'
  password: !secret landin_iot_wifi_password
  domain: '.landin.lan'
  fast_connect: true
  
  manual_ip:
    static_ip: 192.168.10.64
    gateway: 192.168.10.1
    subnet: 255.255.255.0

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret esp_api_password

ota:
  password: !secret esp_ota_password

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "pool house heater button"
    on_press:
      then:
        - switch.turn_on: relay1
        - delay: 1h
        - switch.turn_off: relay1
  - platform: status
    name: "Poolhus Värmare Sonoff status"

switch:
  - platform: gpio
    name: "pool house heater relay"
    pin: GPIO12
    id: relay1