sensor:
  - platform: template
    sensors:
      charge_amps_total_consumption_kwh:
        friendly_name: Total Consumption kWh
        value_template: >-
          {{ state_attr('sensor.charge_amps_charging_status', 'total_consumption_kwh') }}
