climate:
  - platform: generic_thermostat
    name: Poolhus
    heater: switch.poolhus_varmeflakt
    target_sensor: sensor.temperatur_poolhus
    min_cycle_duration:
      minutes: 3
    min_temp: 3
    max_temp: 40
    precision: 1.0
sensor:
  - platform: thermal_comfort
    sensors:
      poolhouse:
        friendly_name: Poolhus
        temperature_sensor: sensor.temperatur_poolhus
        humidity_sensor: sensor.fukt_poolhus
