template:
  - sensor:
      - name: "Nuvarande toppström inkommande faser huvudsäkringar ofiltrerat"
        unique_id: 3b4b7da7-ee15-44b9-a085-5caf25731ec5
        unit_of_measurement: "A"
        state: "{%set mylist = states('sensor.current_phase_1'),states('sensor.current_phase_2'),states('sensor.current_phase_3')%}{{ mylist|max |int(16) }}"
      - name: "Effekt elmätare"
        unique_id: 214a30a7-a59d-4a55-8833-4196137c1677
        unit_of_measurement: "W"
        state: "{{ ((states('sensor.power_produced')|float - states('sensor.power_consumed')|float) * 1000) | round(0)}}"

sensor:
  - platform: filter
    name: "Nuvarande toppström inkommande faser huvudsäkringar"
    entity_id: sensor.nuvarande_toppstrom_inkommande_faser_huvudsakringar_ofiltrerat
    #unique_id: "energy_momentary_max_phase_current_main_fuses"
    filters:
      - filter: time_moving_max
        window_size: "00:02"
      # - filter: outlier
      #   window_size: 3
      #   radius: 2.0
      # - filter: lowpass
      #   time_constant: 3
      #   precision: 0

utility_meter:
  energy_consumption_hourly:
    name: Elkonsumtion per timme
    source: sensor.energy_consumed_luxembourg
    cycle: hourly
