template:
  - sensor:
      - name: "Panna framledning börvärde"
        unique_id: heating_setpoint
        state: "{{ (float(states.input_number.heating_curve.state) * (-1) * float(states.sensor.ow_outside_temp.state) + float(states.input_number.heating_offset.state)) }}"
        unit_of_measurement: "°C"
  - sensor:
      - name: "Lägsta beräknad temperatur panna"
        unique_id: "heating_goal_min_temp"
        state: "{{ (((states.sensor.heating_setpoint.state | float) , (states.input_number.heating_mintemp.state | float)) | max ) }}"
        unit_of_measurement: "°C"
  - binary_sensor:
      - name: "Heating system needed"
        unique_id: heating_system_needed
        state: >
          {{ (states('sensor.temperature_mean_last_month') | float(999)) < 17 }}
  - sensor:
      - name: "Panntemperatur för trendberäkning"
        state: >
          {{ states('sensor.ow_boiler_temp') | float }}

#sensor:
# Utjämnad pelletskurva
# - platform: filter
#   name: "Filtered Pellet Level"
#   entity_id: sensor.pellet_level
#   filters:
#     - filter: time_simple_moving_average
#       window_size: 20
#     - filter: lowpass
#       time_constant: 20
#       precision: 0

# Trend panntemperatur
binary_sensor:
  - platform: trend
    sensors:
      furnace_heating_falling:
        entity_id: sensor.panntemperatur_for_trendberakning
        friendly_name: "Panntemperatur sjunkande"
        sample_duration: 50
        min_gradient: -0.0008
        device_class: cold

      furnace_heating_rising:
        entity_id: sensor.panntemperatur_for_trendberakning
        friendly_name: "Panntemperatur stigande"
        sample_duration: 50
        min_gradient: 0.0008
        device_class: heat

# Kontroller för värme
input_number:
  heating_offset:
    name: Värme offset
    initial: 52
    min: 20
    max: 70
    step: 2
    mode: slider
  heating_curve:
    name: Värmekurva
    initial: 1.4
    min: 1
    max: 2
    step: 0.1
    mode: slider
  heating_mintemp:
    name: Mintemp värmepanna
    initial: 40
    min: 0
    max: 90
    step: 2
    mode: slider
