sensor:
- platform: template
  sensors:
    heating_setpoint:
      unit_of_measurement: "°C"
      friendly_name: "Panna frameledning börvärde"
      value_template: "{{ (float(states.input_number.heating_curve.state) * (-1) * float(states.sensor.ow_outside_temp.state) + float(states.input_number.heating_offset.state)) }}"
    heating_goal_min_temp:
      unit_of_measurement: "°C"
      friendly_name: Lägsta beräknad temperatur panna
      value_template: "{{ (((states.sensor.heating_setpoint.state | float) , (states.input_number.heating_mintemp.state | float)) | max ) }}"
# Utjämnad pelletskurva
- platform: filter
  name: "Filtered Pellet Level"
  entity_id: sensor.pellet_level
  filters:
    - filter: outlier
      window_size: 4
      radius: 4.0
    - filter: lowpass
      time_constant: 10
      precision: 0

# Trend panntemperatur
binary_sensor:
  - platform: trend
    sensors:
      furnace_heating_falling:
        entity_id: sensor.ow_boiler_temp
        friendly_name: "Panntemperatur sjunkande"
        sample_duration: 300
        min_gradient: -0.0008
        device_class: cold

      furnace_heating_rising:
        entity_id: sensor.ow_boiler_temp
        friendly_name: "Panntemperatur stigande"
        sample_duration: 300
        min_gradient: 0.0008
        device_class: heat


# Kontroller för värme
input_number:
  heating_offset:
    name: Värme offset
    initial: 52
    min: 20
    max: 70
    step: 2
    mode: slider
  heating_curve:
    name: Värmekurva
    initial: 1.4
    min: 1
    max: 2
    step: 0.1
    mode: slider
  heating_mintemp:
    name: Mintemp värmepanna
    initial: 40
    min: 0
    max: 90
    step: 2
    mode: slider