rest:
  resource: "http://192.168.10.31/details.xml"
  scan_interval: 60
  sensor:

    - name: "1 wire EDS"
      unique_id: "owserver"
      value_template: "{{ value_json['Devices-Detail-Response']['HostName'] }}"
      force_update: true
      json_attributes_path: "$.['Devices-Detail-Response']"
      json_attributes:
        - MACAddress
        - DeviceName
        - VoltagePower
        - DateTime
        - LoopTime
        - PollCount
        - DevicesConnected
        - DevicesConnectedChannel1
        - DevicesConnectedChannel2
        - DevicesConnectedChannel3
        - VoltageChannel1
        - VoltageChannel2
        - VoltageChannel3
        - DataErrorsChannel1
        - DataErrorsChannel2
        - DataErrorsChannel3

    - name: "ow_kitchen_temp"
      unique_id: owserver.ow_kitchen_temp
      value_template: >
        {% set sensor = (value_json['Devices-Detail-Response']['owd_DS18S20'] | selectattr('ROMId','==','0B0008027C035E10') | list | first) %}
        {% if sensor['Health'] | float >= 7 %}
          {{ sensor['Temperature']['#text'] | round(1) }}
        {% else %} unavailable {% endif %}
      force_update: true
      device_class: temperature
      unit_of_measurement: "°C"
      json_attributes_path: "$.['Devices-Detail-Response']['owd_DS18S20'][?(@.ROMId =='0B0008027C035E10')]"
      json_attributes:
        - Channel
        - Health
        - ROMId

    - name: "ow_pool_temp"
      unique_id: owserver.ow_pool_temp
      value_template: >
        {% set sensor = (value_json['Devices-Detail-Response']['owd_DS18B20'] | selectattr('ROMId','==','DD0119142F965B28') | list | first) %}
        {% if sensor['Health'] | float >= 7 %}
          {{ sensor['Temperature']['#text'] | round(1) }}
        {% else %} unavailable {% endif %}
      force_update: true
      device_class: temperature
      unit_of_measurement: "°C"
      json_attributes_path: "$.['Devices-Detail-Response']['owd_DS18B20'][?(@.ROMId =='DD0119142F965B28')]"
      json_attributes:
        - Channel
        - Health
        - ROMId

    - name: "ow_pool_techroom_temp"
      unique_id: owserver.ow_pool_techroom_temp
      value_template: >
        {% set sensor = (value_json['Devices-Detail-Response']['owd_DS18B20'] | selectattr('ROMId','==','F10119143F90B328') | list | first) %}
        {% if sensor['Health'] | float >= 7 %}
          {{ sensor['Temperature']['#text'] | round(1) }}
        {% else %} unavailable {% endif %}
      force_update: true
      device_class: temperature
      unit_of_measurement: "°C"
      json_attributes_path: "$.['Devices-Detail-Response']['owd_DS18B20'][?(@.ROMId =='F10119143F90B328')]"
      json_attributes:
        - Channel
        - Health
        - ROMId

    - name: "ow_underfloor_return_temp"
      unique_id: owserver.ow_underfloor_return_temp
      value_template: >
        {% set sensor = (value_json['Devices-Detail-Response']['owd_DS18B20'] | selectattr('ROMId','==','19544D550A646128') | list | first) %}
        {% if sensor['Health'] | float >= 7 %}
          {{ sensor['Temperature']['#text'] | round(1) }}
        {% else %} unavailable {% endif %}
      force_update: true
      device_class: temperature
      unit_of_measurement: "°C"
      json_attributes_path: "$.['Devices-Detail-Response']['owd_DS18B20'][?(@.ROMId =='19544D550A646128')]"
      json_attributes:
        - Channel
        - Health
        - ROMId

    - name: "ow_underfloor_out_temp"
      unique_id: owserver.ow_underfloor_out_temp
      value_template: >
        {% set sensor = (value_json['Devices-Detail-Response']['owd_DS18B20'] | selectattr('ROMId','==','E281FF550A646128') | list | first) %}
        {% if sensor['Health'] | float >= 7 %}
          {{ sensor['Temperature']['#text'] | round(1) }}
        {% else %} unavailable {% endif %}
      force_update: true
      device_class: temperature
      unit_of_measurement: "°C"
      json_attributes_path: "$.['Devices-Detail-Response']['owd_DS18B20'][?(@.ROMId =='E281FF550A646128')]"
      json_attributes:
        - Channel
        - Health
        - ROMId

    - name: "ow_boiler_in_temp"
      unique_id: owserver.ow_boiler_in_temp
      value_template: >
        {% set sensor = (value_json['Devices-Detail-Response']['owd_DS18S20'] | selectattr('ROMId','==','340008022A1DEF10') | list | first) %}
        {% if sensor['Health'] | float >= 7 %}
          {{ sensor['Temperature']['#text'] | round(1) }}
        {% else %} unavailable {% endif %}
      force_update: true
      device_class: temperature
      unit_of_measurement: "°C"
      json_attributes_path: "$.['Devices-Detail-Response']['owd_DS18S20'][?(@.ROMId =='340008022A1DEF10')]"
      json_attributes:
        - Channel
        - Health
        - ROMId

    - name: "ow_boiler_out_temp"
      unique_id: owserver.ow_boiler_out_temp
      value_template: >
        {% set sensor = (value_json['Devices-Detail-Response']['owd_DS18S20'] | selectattr('ROMId','==','6D0008022A1AA310') | list | first) %}
        {% if sensor['Health'] | float >= 7 %}
          {{ sensor['Temperature']['#text'] | round(1) }}
        {% else %} unavailable {% endif %}
      force_update: true
      device_class: temperature
      unit_of_measurement: "°C"
      json_attributes_path: "$.['Devices-Detail-Response']['owd_DS18S20'][?(@.ROMId =='6D0008022A1AA310')]"
      json_attributes:
        - Channel
        - Health
        - ROMId

    - name: "ow_boiler_temp"
      unique_id: owserver.ow_boiler_temp
      value_template: >
        {% set sensor = (value_json['Devices-Detail-Response']['owd_DS18B20'] | selectattr('ROMId','==','778A25710A646128') | list | first) %}
        {% if sensor['Health'] | float >= 7 %}
          {{ sensor['Temperature']['#text'] | round(1) }}
        {% else %} unavailable {% endif %}
      force_update: true
      device_class: temperature
      unit_of_measurement: "°C"
      json_attributes_path: "$.['Devices-Detail-Response']['owd_DS18B20'][?(@.ROMId =='778A25710A646128')]"
      json_attributes:
        - Channel
        - Health
        - ROMId

    - name: "ow_outside_temp"
      unique_id: owserver.ow_outside_temp
      value_template: >
        {% set sensor = (value_json['Devices-Detail-Response']['owd_DS18S20'] | selectattr('ROMId','==','560008022A0D0E10') | list | first) %}
        {% if sensor['Health'] | float >= 7 %}
          {{ sensor['Temperature']['#text'] | round(1) }}
        {% else %} unavailable {% endif %}
      force_update: true
      device_class: temperature
      unit_of_measurement: "°C"
      json_attributes_path: "$.['Devices-Detail-Response']['owd_DS18S20'][?(@.ROMId =='560008022A0D0E10')]"
      json_attributes:
        - Channel
        - Health
        - ROMId
