homeassistant:
  customize:
    # sensor.ow_boiler_temp_rounded:
    #   friendly_name: 'Panntemperatur'
    #   icon: mdi:oil-temperature
    # sensor.ow_boiler_out_temp_rounded:
    #   friendly_name: 'Panna temperatur ut'
    #   icon: mdi:oil-temperature
    # sensor.ow_outside_temp_rounded:
    #   friendly_name: 'Utetemperatur'
    #   icon: mdi:thermometer
    # sensor.ow_pool_techroom_temp_rounded:
    #   friendly_name: 'Temp Teknikshakt'
    #   icon: mdi:thermometer
    sensor.ow_pool_techroom_temp:
      hidden: true
    sensor.ow_pool_temp:
      hidden: true
    sensor.ow_outside_temp:
      hidden: true
    sensor.ow_boiler_temp:
      hidden: true
    sensor.ow_boiler_out_temp:
      hidden: true
  
sensor:
- platform: snmp
  name: ow_boiler_temp
  host: 192.168.10.31
  baseoid: 1.3.6.1.4.1.31440.10.6.1.1.1
  scan_interval: 30

- platform: snmp
  name: ow_boiler_out_temp
  host: 192.168.10.31
  baseoid: 1.3.6.1.4.1.31440.10.6.1.1.2
  scan_interval: 30

- platform: snmp
  name: ow_outside_temp
  host: 192.168.10.31
  baseoid: 1.3.6.1.4.1.31440.10.6.1.1.5
  scan_interval: 1800

- platform: snmp
  name: ow_pool_temp
  host: 192.168.10.31
  baseoid: 1.3.6.1.4.1.31440.10.5.1.1.10
  scan_interval: 600

- platform: snmp
  name: ow_pool_techroom_temp
  host: 192.168.10.31
  baseoid: 1.3.6.1.4.1.31440.10.6.1.1.6
  scan_interval: 600


- platform: template
  sensors:
    ow_outside_temp_rounded:
      unit_of_measurement: "°C"
      friendly_name: "Ute"
      #icon: mdi:thermometer
      value_template: "{{ (states.sensor.ow_outside_temp.state|round(1)) }}"
    ow_boiler_temp_rounded:
      unit_of_measurement: "°C"
      friendly_name: "Panna"
      #icon: mdi:coolant-temperature
      value_template: "{{ (states.sensor.ow_boiler_temp.state|round(1)) }}"
    ow_boiler_out_temp_rounded:
      unit_of_measurement: "°C"
      friendly_name: "Panna framledning"
      #icon: mdi:coolant-temperature
      value_template: "{{ (states.sensor.ow_boiler_out_temp.state|round(1)) }}"
    ow_pool_temp_rounded:
      unit_of_measurement: "°C"
      friendly_name: "Pool"
      #icon: mdi:pool
      value_template: "{{ (states.sensor.ow_pool_temp.state|round(1)) }}"
    ow_pool_techroom_temp_rounded:
      unit_of_measurement: "°C"
      friendly_name: "Teknikshakt"
      #icon: mdi:thermometer
      value_template: "{{ (states.sensor.ow_pool_techroom_temp.state|round(1)) }}"