homeassistant:
  customize:
    sensor.ow_pool_techroom_temp:
      hidden: true
    sensor.ow_pool_temp:
      hidden: true
    sensor.ow_outside_temp:
      hidden: true
    sensor.ow_boiler_temp:
      hidden: true
    sensor.ow_boiler_out_temp:
      hidden: true
    sensor.ow_kitchen_temp:
      hidden: true

# Use MIB Browser on Carson to find OIDs

sensor:
  - platform: snmp
    name: ow_boiler_temp
    host: 192.168.10.31
    baseoid: 1.3.6.1.4.1.31440.10.6.1.1.1
    scan_interval: 30

  - platform: snmp
    name: ow_boiler_out_temp
    host: 192.168.10.31
    baseoid: 1.3.6.1.4.1.31440.10.6.1.1.3
    scan_interval: 30

  - platform: snmp
    name: ow_outside_temp
    host: 192.168.10.31
    baseoid: 1.3.6.1.4.1.31440.10.6.1.1.2
    scan_interval: 1800

  - platform: snmp
    name: ow_pool_temp
    host: 192.168.10.31
    baseoid: 1.3.6.1.4.1.31440.10.5.1.1.7
    scan_interval: 600

  - platform: snmp
    name: ow_pool_techroom_temp
    host: 192.168.10.31
    baseoid: 1.3.6.1.4.1.31440.10.6.1.1.5
    scan_interval: 600

  - platform: snmp
    name: ow_kitchen_temp
    host: 192.168.10.31
    baseoid: 1.3.6.1.4.1.31440.10.6.1.1.6
    scan_interval: 600

    # Temperaturmedel över dygnet
  - platform: statistics
    name: "Temperature Mean last day"
    entity_id: sensor.ow_outside_temp_rounded
    state_characteristic: mean
    precision: 0
    sampling_size: 1500
    max_age:
      hours: 24

  # Temperaturmedel över veckan
  - platform: statistics
    name: "Temperature Mean last week"
    entity_id: sensor.ow_outside_temp_rounded
    state_characteristic: mean
    precision: 0
    sampling_size: 1500
    max_age:
      days: 7

  # Temperaturmedel över månaden
  - platform: statistics
    name: "Temperature Mean last month"
    entity_id: sensor.ow_outside_temp_rounded
    state_characteristic: mean
    precision: 0
    sampling_size: 1500
    max_age:
      days: 31

template:
  - binary_sensor:
      - name: "Senaste veckans medeltemperatur under 10 grader"
        state: "{{ states('sensor.temperature_mean_last_week') | float < 10 }}"
        unique_id: "41b1a348-4fc4-41be-ae14-5b1432fe2218"

  - sensor:
      - name: ow_outside_temp_rounded
        unit_of_measurement: "°C"
        state: "{{ (states('sensor.ow_outside_temp') | round(1)) }}"
        attributes:
          friendly_name: "Ute"
      - name: ow_boiler_temp_rounded
        unit_of_measurement: "°C"
        attributes:
          friendly_name: "Panna"
        state: "{{ (states('sensor.ow_boiler_temp') | round(1)) }}"
      - name: ow_boiler_out_temp_rounded
        unit_of_measurement: "°C"
        attributes:
          friendly_name: "Panna framledning"
        state: "{{ (states('sensor.ow_boiler_out_temp')|round(1)) }}"
      - name: ow_pool_temp_rounded
        unit_of_measurement: "°C"
        attributes:
          friendly_name: "Pool"
        state: "{{ (states('sensor.ow_pool_temp')|round(1)) }}"
      - name: ow_pool_techroom_temp_rounded
        unit_of_measurement: "°C"
        attributes:
          friendly_name: "Teknikshakt"
        state: "{{ (states('sensor.ow_pool_techroom_temp')|round(1)) }}"
      - name: ow_kitchen_temp_rounded
        unit_of_measurement: "°C"
        attributes:
          friendly_name: "Köket"
        state: "{{ (states('sensor.ow_kitchen_temp')|round(1)) }}"


  # - platform: template
  #   sensors:
  #     # ow_outside_temp_rounded:
  #     #   unit_of_measurement: "°C"
  #     #   friendly_name: "Ute"
  #     #   icon_template: mdi:thermometer
  #     #   value_template: "{{ (states.sensor.ow_outside_temp.state|round(1)) }}"
  #     ow_boiler_temp_rounded:
  #       unit_of_measurement: "°C"
  #       friendly_name: "Panna"
  #       icon_template: mdi:coolant-temperature
  #       value_template: "{{ (states.sensor.ow_boiler_temp.state|round(1)) }}"
  #     ow_boiler_out_temp_rounded:
  #       unit_of_measurement: "°C"
  #       friendly_name: "Panna framledning"
  #       icon_template: mdi:coolant-temperature
  #       value_template: "{{ (states.sensor.ow_boiler_out_temp.state|round(1)) }}"
  #     ow_pool_temp_rounded:
  #       unit_of_measurement: "°C"
  #       friendly_name: "Pool"
  #       icon_template: mdi:pool
  #       value_template: "{{ (states.sensor.ow_pool_temp.state|round(1)) }}"
  #     ow_pool_techroom_temp_rounded:
  #       unit_of_measurement: "°C"
  #       friendly_name: "Teknikshakt"
  #       icon_template: mdi:thermometer
  #       value_template: "{{ (states.sensor.ow_pool_techroom_temp.state|round(1)) }}"
  #     ow_kitchen_temp_rounded:
  #       unit_of_measurement: "°C"
  #       friendly_name: "Köket"
  #       value_template: "{{ (states.sensor.ow_kitchen_temp.state|round(1)) }}"
  #       icon_template: mdi:thermometer
