homeassistant:
  customize:
    sensor.ow_pool_techroom_temp:
      hidden: true
    sensor.ow_pool_temp:
      hidden: true
    sensor.ow_outside_temp:
      hidden: true
    sensor.ow_boiler_temp:
      hidden: true
    sensor.ow_boiler_out_temp:
      hidden: true
    sensor.ow_kitchen_temp:
      hidden: true

# Use MIB Browser on Carson to find OIDs

sensor:
  - platform: snmp
    name: ow_boiler_temp
    host: 192.168.10.31
    baseoid: 1.3.6.1.4.1.31440.10.6.1.1.1
    scan_interval: 30

  - platform: snmp
    name: ow_boiler_out_temp
    host: 192.168.10.31
    baseoid: 1.3.6.1.4.1.31440.10.6.1.1.3
    scan_interval: 30

  - platform: snmp
    name: ow_outside_temp
    host: 192.168.10.31
    baseoid: 1.3.6.1.4.1.31440.10.6.1.1.2
    scan_interval: 30

  - platform: snmp
    name: ow_pool_temp
    host: 192.168.10.31
    baseoid: 1.3.6.1.4.1.31440.10.5.1.1.10
    scan_interval: 30

  - platform: snmp
    name: ow_pool_techroom_temp
    host: 192.168.10.31
    baseoid: 1.3.6.1.4.1.31440.10.5.1.1.11
    scan_interval: 30

  - platform: snmp
    name: ow_kitchen_temp
    host: 192.168.10.31
    baseoid: 1.3.6.1.4.1.31440.10.6.1.1.6
    scan_interval: 30

    # Temperaturmedel över dygnet
  - platform: statistics
    name: "Temperature Mean last day"
    entity_id: sensor.ow_outside_temp_rounded
    state_characteristic: mean
    precision: 0
    sampling_size: 1500
    max_age:
      hours: 24

  # Temperaturmedel över veckan
  - platform: statistics
    name: "Temperature Mean last week"
    entity_id: sensor.ow_outside_temp_rounded
    state_characteristic: mean
    precision: 0
    sampling_size: 1500
    max_age:
      days: 7

  # Temperaturmedel över månaden
  - platform: statistics
    name: "Temperature Mean last month"
    entity_id: sensor.ow_outside_temp_rounded
    state_characteristic: mean
    precision: 0
    sampling_size: 1500
    max_age:
      days: 31

template:
  - binary_sensor:
      - name: "Senaste veckans medeltemperatur under 10 grader"
        state: >
          {% if not is_state('sensor.temperature_mean_last_week', 'unavailable') %}
          {{ states('sensor.temperature_mean_last_week') | float < 10 }}
          {% endif %}
        unique_id: "41b1a348-4fc4-41be-ae14-5b1432fe2218"

  - sensor:
      - name: ow_outside_temp_rounded
        unique_id: 283a3670-b909-46d8-bfa6-749e70a03866
        unit_of_measurement: "°C"
        state: "{{ (states('sensor.ow_outside_temp') | round(1)) }}"

      - name: ow_boiler_temp_rounded
        unique_id: e878a1b4-375c-4b41-b967-2885adc612c9
        unit_of_measurement: "°C"
        state: "{{ (states('sensor.ow_boiler_temp') | round(1)) }}"

      - name: ow_boiler_out_temp_rounded
        unique_id: 44cec4b6-352e-4040-a792-aa051951ca4a
        unit_of_measurement: "°C"
        state: "{{ (states('sensor.ow_boiler_out_temp')|round(1)) }}"

      - name: ow_pool_temp_rounded
        unique_id: 4cc0e228-30b5-4e8a-8ccc-c59dbc46058c
        unit_of_measurement: "°C"
        state: "{{ (states('sensor.ow_pool_temp')|round(1)) }}"

      - name: ow_pool_techroom_temp_rounded
        unique_id: f12593c0-879d-4164-b86e-9579939a2923
        unit_of_measurement: "°C"
        state: "{{ (states('sensor.ow_pool_techroom_temp')|round(1)) }}"

      - name: ow_kitchen_temp_rounded
        unique_id: f08cbc34-e72a-4cb8-abd9-26778303bc99
        unit_of_measurement: "°C"
        state: "{{ (states('sensor.ow_kitchen_temp')|round(1)) }}"
