homeassistant:
  automations:
    - id: '12345'
      alias: Pellet level warning 50%
      trigger:
      - above: '20'
        below: '50'
        entity_id: sensor.pellet_level_2
        for:
          hours: 1
        platform: numeric_state
      condition:
      - condition: template
        value_template: '{{ as_timestamp(now()) - as_timestamp(states.automation.pellet_level_warning_50.attributes.last_triggered)
          | int > 86400 }}'
      action:
      - data:
          message: Det är cirka 50 procent pellets i tunnan
        service: notify.slack_notify
    - id: '23456'
      alias: Pellet level warning 20%
      trigger:
      - above: '0.0'
        below: '20'
        entity_id: sensor.pellet_level_2
        for:
          hours: 1
        platform: numeric_state
      condition:
      - condition: template
        value_template: '{{ as_timestamp(now()) - as_timestamp(states.automation.pellet_level_warning_20.attributes.last_triggered)
          | int > 86400 }}'
      action:
      - data:
          message: Det är cirka 20 procent pellets i tunnan
        service: notify.slack_notify