sensor:
  - platform: daily_min_max
    name: Pellets Kg Daily Min
    unique_id: pellets_kg_daily_min
    type: min
    manual_reset_only: true
    entity_ids:
      - sensor.pellets_kg

template:
  - sensor:
      - name: pellets_kg_daily_min_inverted
        unit_of_measurement: "Kg"
        state: >
          {{ states('sensor.pellets_kg_daily_min') | float * -1.0 }}
  - sensor:
      - name: "Pelletspris"
        unit_of_measurement: "Öre/kWh"
        unique_id: 537d3154-1d86-44fe-9e52-fe62304a0a11
        state: >
          {% set pris_per_sack = states('input_number.pelletssackar_pris') | float(0) %}
          {% set kg_per_sack = 16 %}
          {% set verkningsgrad = 0.91 %}
          {% set kwh_per_kg = 4.8 %}
          {% set ore = ((pris_per_sack / kg_per_sack) / verkningsgrad) / kwh_per_kg * 100 %}
          {{ ore | round(2) }}
        # Pannans verkningsgrad 91%, Pellets 4,8 kWh/kg, 16kg pellets per säck
  - sensor:
      - name: "Pelletspris kronor"
        unit_of_measurement: "Kr/kWh"
        unique_id: 0a8f94ea-a723-45ea-b881-b6f3c2677ad4
        state: >
          {{ states('sensor.pelletspris') | float(0) / 100 }}
  - sensor:
      - name: "Beräkning slut på pellets"
        unit_of_measurement: "dagar"
        unique_id: a2ab8cc7-502f-4383-b286-30d1cc0925f1
        state: >
          {% set sacks = (states('counter.pelletssackar_lager') | int(0))
                        + (states('sensor.pelletsackar_i_veckoforrad') | float(0)) %}
          {% set kg_per_sack = 16 %}
          {% set daily       = states('sensor.daily_pellets') | float(0) %}
          {% set daily_last  = state_attr('sensor.daily_pellets','last_period') | float(0) %}
          {% set weekly      = (states('sensor.weekly_pellets') | float(0)) / 7 %}
          {% set weekly_last = (state_attr('sensor.weekly_pellets','last_period') | float(0)) / 7 %}
          {% set usage = [daily, daily_last, weekly, weekly_last] | max %}
          {% if usage > 0 %}
            {{ (sacks * kg_per_sack / usage) | round(0) }}
          {% else %}
            {{ '' }}  {# unknown instead of division by zero #}
          {% endif %}
  - sensor:
      - name: "Panna konsumtion pellets"
        unit_of_measurement: kWh
        unique_id: 0d3ec94c-ad46-478d-8908-66b55eb496bb
        state_class: total_increasing
        device_class: energy
        state: >
          {{ states('sensor.yearly_pellets') | float(0) * 4.8 }}

utility_meter:
  daily_pellets:
    source: sensor.pellets_kg_daily_min_inverted
    cycle: daily
    unique_id: daily_pellets
    net_consumption: false
  weekly_pellets:
    source: sensor.pellets_kg_daily_min_inverted
    cycle: weekly
    unique_id: weekly_pellets
    net_consumption: false
  monthly_pellets:
    source: sensor.pellets_kg_daily_min_inverted
    cycle: monthly
    unique_id: monthly_pellets
    net_consumption: false
  quarterly_pellets:
    source: sensor.pellets_kg_daily_min_inverted
    cycle: quarterly
    unique_id: quarterly_pellets
    net_consumption: false
  yearly_pellets:
    source: sensor.pellets_kg_daily_min_inverted
    unique_id: yearly_pellets
    cron: "0 0 1 6 *"
    net_consumption: false
  pellets_kg_since_last_clean:
    unique_id: pellets_kg_since_last_clean
    source: sensor.pellets_kg_daily_min_inverted
    net_consumption: false
  pellets_kg_since_last_fill:
    unique_id: pellets_kg_since_last_fill
    source: sensor.pellets_kg_daily_min_inverted
    net_consumption: false
