sensor:
  - platform: history_stats
    name: Pool circulation active daytime
    entity_id: switch.cirk_pump_pool
    state: "on"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0, microsecond=0) }}"
    #end: "{{ now().replace(hour=20, minute=0, second=0, microsecond=0) }}"
    duration:
      hours: 24

template:
  - binary_sensor:
      - name: För kallt för att bada
        state: >
          {{ states('sensor.ow_pool_temp_rounded')|float < 16 }}
        unique_id: 68821f3c-8ec7-4e56-a938-03842faa90cf
