sensor:
  - platform: resrobot
    fetch_interval: 30
    key: !secret trafiklab
    departures:
      - stop_id: 740072471
        name: "Buss till Botulfsplatsen"
        max_journeys: 20
        sensors: 3
        unit: "游뎸"
        time_format: "%H:%M"
        filter:
          - line: 5
            type: "contains"
            direction: "annehem"
      - stop_id: 740016732
        name: "Bussar fr친n Gastelyckan 칐"
        max_journeys: 20
        sensors: 6
        unit: "游뎸"
        time_format: "%H:%M"
        filter:
          - direction: "Lund C"
      - stop_id: 740016981
        name: "Bussar fr친n Botulfsplatsen"
        max_journeys: 20
        sensors: 3
        unit: "游뎸"
        time_format: "%H:%M"
        filter:
          - line: 5
            direction: "Lund R친bylund"
      - stop_id: 740016757
        name: "Bussar fr친n Bankgatan"
        max_journeys: 20
        sensors: 2
        unit: "游뎸"
        time_format: "%H:%M"
        filter:
          - line: 161
          - line: 162
