sensor:
  - platform: resrobot
    fetch_interval: 10
    key: !secret trafiklab
    departures:
      - stop_id: 740072471
        name: "Buss till Stortorget"
        max_journeys: 20
        sensors: 3
        unit: "🕑"
        time_format: "%H:%M"
        filter:
          - line: 5
            type: "contains"
            direction: "annehem"
      - stop_id: 740016732
        name: "Bussar från Gastelyckan Ö"
        max_journeys: 20
        sensors: 6
        unit: "🕑"
        time_format: "%H:%M"
        filter:
          - direction: "Lund C"
      - stop_id: 740077054
        name: "Bussar från Stortorget"
        max_journeys: 20
        sensors: 3
        unit: "🕑"
        time_format: "%H:%M"
        filter:
          - line: 5
            direction: "Lund Råbylund"
      - stop_id: 740016757
        name: "Bussar från Bankgatan"
        max_journeys: 20
        sensors: 2
        unit: "🕑"
        time_format: "%H:%M"
        filter:
          - line: 161
          - line: 162
