sensor:
  - platform: rest
    resource: "https://opendata-download-metobs.smhi.se/api/version/1.0/parameter/5/station/53430/period/latest-day/data.json"
    name: Regn Lund
    authentication: basic
    headers:
      User-Agent: Home Assistant
      Content-Type: application/json
    scan_interval: 3600
    value_template: "{{ value_json.value.0.value if int(value_json.value.0.value) > 0 }}"
    unit_of_measurement: "mm"

  - platform: statistics
    name: Regn Lund senaste 7 dagar
    state_characteristic: total
    entity_id: sensor.regn_lund
    max_age:
      days: 7
    sampling_size: 50
